name: Auto Update RSS Feed

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours (00:00 & 12:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS generator script
        run: python igaming_rss_edge.py

      - name: Commit and push only if feed changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add igamingontario_feed_v2.xml

          CHANGED=$(git diff --cached --quiet || echo "yes")

          if [ "$CHANGED" = "yes" ]; then
            echo "✅ Feed changed — committing and pushing"
            git commit -m "⏰ Auto-update RSS feed"
            git push origin HEAD:main
          else
            echo "🟡 No changes to commit — skipping push"
          fi
