name: Auto Update iGaming RSS Feed

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Switch to main branch
        run: git checkout main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS generator script
        run: python igaming_rss_edge.py igamingontario_feed_v3.xml

      - name: Commit and push only if feed content changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if [ ! -f igamingontario_feed_v3.xml ]; then
            echo "❌ RSS file not found. Skipping commit."
            exit 0
          fi

          if git diff --quiet --exit-code igamingontario_feed_v3.xml; then
            echo "🟡 No content changes — skipping commit"
            exit 0
          fi

          git add igamingontario_feed_v3.xml
          git commit -m "⏰ Auto-update iGaming feed (v3)"
          git push origin main
